name: Scrape Site Tables

on:
  workflow_dispatch: # manual trigger
  schedule:
    - cron: '0 2 * * *' # daily at 2 AM UTC

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run scraping script
        run: npm run scrape
